# ML Collections is a library of Python Collections designed for ML usecases.

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

exports_files(["LICENSE"])

py_library(
    name = "ml_collections",
    srcs = [
        "__init__.py",
    ],
    srcs_version = "PY2AND3",
    deps = [
        "//ml_collections/config_dict",
    ],
)
