# ConfigDict is a dict like class used for expressing configurations of experiments and models.

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

py_library(
    name = "config_dict",
    srcs = [
        "__init__.py",
        "config_dict.py",
    ],
    srcs_version = "PY2AND3",
    deps = [
        # pip: absl/logging
        # pip: contextlib2
        # pip: six
        # pip: yaml
    ],
)
